// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi_4mBWfq049VZRpruGNc4w1gBI_0ehNc',
    appId: '1:1033008843718:web:a1461895f7a1810cdac0c7',
    messagingSenderId: '1033008843718',
    projectId: 'voyage-trip-planner-c7623',
    authDomain: 'voyage-trip-planner-c7623.firebaseapp.com',
    storageBucket: 'voyage-trip-planner-c7623.firebasestorage.app',
    measurementId: 'G-GXPRYPR20B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZd0eH-HG2M9P3JAJkm_zJWC2oJ3uHRGc',
    appId: '1:1033008843718:android:48e176f4a8fbf105dac0c7',
    messagingSenderId: '1033008843718',
    projectId: 'voyage-trip-planner-c7623',
    storageBucket: 'voyage-trip-planner-c7623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1HZ7H1r1FxYhJtAXRFdfF-KGj1PNX-WM',
    appId: '1:1033008843718:ios:7719f9275adba042dac0c7',
    messagingSenderId: '1033008843718',
    projectId: 'voyage-trip-planner-c7623',
    storageBucket: 'voyage-trip-planner-c7623.firebasestorage.app',
    iosBundleId: 'com.example.voyageFlutter',
  );
}
